"""empty message

Revision ID: ba406da008a2
Revises: bb1de56898eb
Create Date: 2020-07-15 23:18:03.198401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = 'ba406da008a2'
down_revision = 'bb1de56898eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=80), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    
    
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
